# Generated by Django 4.0.1 on 2022-02-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('hotel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hotel')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('booked_from', models.DateField(blank=True, null=True)),
                ('booked_to', models.DateField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='room.category', to_field='name')),
                ('hotel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hotel')),
            ],
        ),
    ]
