# Generated by Django 4.0 on 2022-02-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('hotel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room', to_field='number')),
            ],
        ),
    ]
